# Generated by Django 3.1.2 on 2020-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('emailFrom', models.EmailField(max_length=256)),
                ('emailTo', models.EmailField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
