# Generated by Django 3.1.2 on 2020-10-28 11:37

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=65535)),
                ('emailFrom', models.EmailField(max_length=256)),
                ('emailTo', models.EmailField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', django_fsm.FSMField(blank=True, default='old', max_length=50, null=True)),
                ('task_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(max_length=256)),
                ('EMAIL_PORT', models.PositiveSmallIntegerField()),
                ('EMAIL_HOST_USER', models.CharField(max_length=256)),
                ('EMAIL_HOST_PASSWORD', models.CharField(max_length=256)),
            ],
        ),
    ]
