# Generated by Django 3.1.2 on 2020-10-22 14:01

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=django_fsm.FSMField(default='old', max_length=50),
        ),
    ]
