# Generated by Django 3.1.2 on 2020-10-28 18:24

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='status',
        ),
        migrations.AddField(
            model_name='email',
            name='user_clicked',
            field=django_fsm.FSMField(default='False', max_length=50),
        ),
    ]
