# Generated by Django 3.1.2 on 2020-10-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='name',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.CharField(max_length=65535),
        ),
    ]
