# Generated by Django 3.1.2 on 2020-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0002_email_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(max_length=256)),
                ('EMAIL_PORT', models.PositiveSmallIntegerField()),
                ('EMAIL_HOST_USER', models.CharField(max_length=256)),
                ('EMAIL_HOST_PASSWORD', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='status',
        ),
    ]
